# Lab. 2
Wiktor Kurek, Dawid Stachowiak

# Zadanie 1

In [2]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_breast_cancer
print(load_breast_cancer().data)
print(load_breast_cancer().target)

[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 1 0 1 1 1 1 1 0 0 1 0 0 1 1 1 1 0 1 0 0 1 1 1 1 0 1 0 0
 1 0 1 0 0 1 1 1 0 0 1 0 0 0 1 1 1 0 1 1 0 0 1 1 1 0 0 1 1 1 1 0 1 1 0 1 1
 1 1 1 1 1 1 0 0 0 1 0 0 1 1 1 0 0 1 0 1 0 0 1 0 0 1 1 0 1 1 0 1 1 1 1 0 1
 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 1 0 1 1 0 0 1 1 0 0 1 1 1 1 0 1 1 0 0 0 1 0
 1 0 1 1 1 0 1 1 0 0 1 0 0 0 0 1 0 0 0 1 0 1 0 1 1 0 1 0 0 0 0 1 1 0 0 1 1
 1 0 1 1 1 1 1 0 0 1 1 0 1 1 0 0 1 0 1 1 1 1 0 1 1 1 1 1 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 1 1 1 1 1 0 1 0 1 1 0 1 1 0 1 0 0 1 1 1 1 1 1 1 1 

In [3]:
data = load_breast_cancer().data
target = load_breast_cancer().target

### 1. Wymiar wczytanych danych

In [4]:
print(data.shape)
print(target.shape)

(569, 30)
(569,)


### 2. Ilość wartości unikatowych w wektorze target

In [5]:
list(set(target))

[0, 1]

### 3. Zaproponuj usunięcie tych kolumn ze zbioru danych, które Twoim zdaniem dostarczają najmniej informacji

In [6]:
data = data[:,:20] #usuwam 10 ostatnich kolumn (worst) poniewaz dają nam informacje tylko o skrajnej wartości jednego pomairu

### 4. Zapisz w pliku dataset_cut.csv wypadkowy zbiór danych jak poniżej: ColName1; ColName2; …; TARGET

In [7]:
features = load_breast_cancer().feature_names[:20]
features = np.append (features, ['TARGET'])
dataset = np.append(data, target.reshape(569,1), axis=1)
print(dataset.shape)
df = pd.DataFrame(data = dataset, columns = features)
df.to_csv("dataset_cut.csv")

(569, 21)


# Zadanie 2

### 1. Wprowadź zbiór danych do algorytmu PCA
### 2. Wykonaj redukcję wymiarowości do 5 wymiarów wypadkowego zbioru danych

In [8]:
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

standarized = StandardScaler().fit_transform(data)
pca = PCA(n_components = 5)
reduced = pca.fit_transform(standarized)
print(reduced)
reduced_df = pd.DataFrame(reduced)
print(reduced_df.shape)

[[ 7.08351496  0.68905184 -1.97759299 -2.41601264  1.7881753 ]
 [ 1.13678036 -3.22466166 -0.42666245  0.38989184  0.7887873 ]
 [ 4.40230338 -1.46673681 -0.90834385 -0.18179909  0.03645464]
 ...
 [ 0.85472157 -1.47573878  0.66606694  2.09940824 -0.86371105]
 [ 7.41150964  0.11856378 -1.13090005  0.17313771 -2.64128003]
 [-4.09694916 -0.01290673  2.66523117  0.39004325 -0.39297542]]
(569, 5)


### 3. Zapisz w pliku dataset_pca_5.csv wypadkowy zbiór danych jak poniżej: COMP1; COMP2; COMP3; COMP4; COMP5; TARGET

In [9]:
features = ['COMP1', 'COMP2', 'COMP3', 'COMP4', 'COMP5', 'TARGET']
dataset = np.append(reduced, target.reshape(569,1), axis=1)
print(dataset.shape)
df = pd.DataFrame(data = dataset, columns = features)
df.to_csv("dataset_pca_5.csv")

(569, 6)


### 4. Oblicz wariancję zbioru danych po redukcji wymiarowości

In [10]:
import statistics as stat
print(reduced.var())
#lub
print(stat.variance(reduced.flatten()))
print(df.var())

3.3868560510357937
3.3880469286908705
COMP1     8.745573
COMP2     4.168247
COMP3     1.718822
COMP4     1.309718
COMP5     1.021735
TARGET    0.234177
dtype: float64


### 5. Oblicz wartość wariancji wyjaśnionej dla wygenerowanych składowych (ang.explained variance ratio)

In [11]:
pca.explained_variance_ratio_

array([0.43651014, 0.20804607, 0.08579006, 0.06537079, 0.05099695])

### 6. Skomentuj otrzymane rezultaty.
  
  Wariancja całego zbioru po redukcji wymiarowości wzrosła wielokrotnie, co oznacza że po tej operacji zróżnicowanie cech w naszym zbiorze wzrosło.

# Zadanie 3

In [12]:
data_new = load_breast_cancer().data
target_new = load_breast_cancer().target

In [13]:
data_new = data_new[:,:20]

### 1. Uzasadnij optymalny wymiar zbioru danych zakładając, że w zbiorze wypadkowym suma składowych będzie stanowiła minimum 90% wariancji.
### 2. Wykonaj redukcję wymiarowości za pomocą algorytmu PCA.

In [14]:
standarized_new = StandardScaler().fit_transform(data_new)
pca_new = PCA(.90)
reduced_new = pca_new.fit_transform(standarized_new)
print(reduced_new)
df_reduced = pd.DataFrame(data = reduced_new)
print(df_reduced.shape)

[[ 7.08351496  0.68905184 -1.97759301 ...  1.78817534 -0.79021754
  -1.74916791]
 [ 1.13678036 -3.22466166 -0.42666245 ...  0.78878731 -0.18664794
   0.49650704]
 [ 4.40230338 -1.46673681 -0.90834384 ...  0.03645473 -0.31847824
   0.55624229]
 ...
 [ 0.85472157 -1.47573878  0.66606695 ... -0.86371106  0.37005545
  -0.0670664 ]
 [ 7.41150964  0.11856378 -1.13090005 ... -2.64128011 -0.39100681
  -0.23455732]
 [-4.09694916 -0.01290673  2.66523116 ... -0.39297531 -0.94600428
  -1.47397124]]
(569, 7)


### 3. Zapisz w pliku dataset_pca_n.csv wypadkowy zbiór danych jak poniżej: COMP1; COMP2; COMP3; COMP4; ...; COMPN; TARGET

In [15]:
features_new = ['COMP1', 'COMP2', 'COMP3', 'COMP4', 'COMP5', 'COMP6', 'COMP7', 'TARGET']
dataset_new = np.append(reduced_new, target_new.reshape(569,1), axis=1)
print(dataset_new.shape)
df_new = pd.DataFrame(data = dataset_new, columns = features_new)
df_new.to_csv("dataset_pca_n.csv")

(569, 8)


### 4. Oblicz wartość wariancji wyjaśnionej dla wygenerowanych składowych (ang. explained variance ratio)

In [16]:
print(reduced_new.var())
print(df_new.var())

2.6027957151624883
COMP1     8.745573
COMP2     4.168247
COMP3     1.718822
COMP4     1.309718
COMP5     1.021735
COMP6     0.750052
COMP7     0.537501
TARGET    0.234177
dtype: float64


In [17]:
pca_new.explained_variance_ratio_

array([0.43651014, 0.20804607, 0.08579006, 0.06537079, 0.05099695,
       0.03743668, 0.02682781])

### 5. Skomentuj otrzymane rezultaty.
Ponownie wariancja poszczególnych kolumn wzrosła, jednak przy kolejnych kolumnach te wzrosty są coraz mniejsze i bliższe wartości wariancji wyjaśnione.

# Zadanie 4
Wykonaj redukcję wymiarowości na podstawie dowolnego innego algorytmu a wynik zapisz w pliku dataset_algorithm.csv. Skomentuj otrzymane rezultaty.

In [18]:
from sklearn.manifold import TSNE
tsne = TSNE(n_components=2).fit_transform(data_new)

In [26]:
print(tsne.shape)
features_new = ['COMP1', 'COMP2', 'TARGET']
dataset_new = np.append(tsne, target_new.reshape(569,1), axis=1)
print(dataset_new.shape)
df_tsne = pd.DataFrame(data = dataset_new, columns = features_new)
df_tsne.to_csv("dataset_tsne.csv")

(569, 2)
(569, 3)
